cmake_minimum_required(VERSION 3.8)
project(fanuc_m10ia_control)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(moveit_ros_planning_interface REQUIRED)
find_package(moveit_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(shape_msgs REQUIRED)
find_package(moveit_core REQUIRED)
find_package(moveit_ros_planning REQUIRED)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

add_executable(planning_scene src/planning_scene.cpp)

ament_target_dependencies(planning_scene
  rclcpp
  moveit_ros_planning_interface
  moveit_msgs
  geometry_msgs
  shape_msgs
)

install(TARGETS
  planning_scene
  DESTINATION lib/${PROJECT_NAME}
)

add_executable(path_length src/path_length.cpp)

ament_target_dependencies(path_length
  rclcpp
  moveit_msgs
)

install(TARGETS
  path_length
  DESTINATION lib/${PROJECT_NAME}
)

install(TARGETS
  path_length
  DESTINATION lib/${PROJECT_NAME}
)

add_executable(jacobiano_moveit src/jacobiano_moveit.cpp)

ament_target_dependencies(jacobiano_moveit
  rclcpp
  moveit_core
  moveit_ros_planning
)

install(TARGETS
  jacobiano_moveit
  DESTINATION lib/${PROJECT_NAME}
)

ament_package()

